### ISSUE TITLE
[New] New support of Python 3.10

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#1147]
## Summary of this new feature
To support Python 3.10, add tests with Python 3.10.

CovsirPhy version I used: 2.25.0

**Comment by lisphilar** [comment]
Reference for full test with Python 3.10
https://github.com/actions/setup-python/issues/160

**Comment by lisphilar** [comment]
The following error was raised.
```Bash
       Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'ext' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-install-nfd3s0t1/datatable_a3070a130bc54a49a8069aebae7b80c1/ci/ext.py", line 587, in build_wheel
          so_file = build_extension(cmd=("debug" if debug_wheel else "build"),
        File "/tmp/pip-install-nfd3s0t1/datatable_a3070a130bc54a49a8069aebae7b80c1/ci/ext.py", line 360, in build_extension
          ext.build()
        File "/tmp/pip-install-nfd3s0t1/datatable_a3070a130bc54a49a8069aebae7b80c1/ci/xbuild/extension.py", line 439, in build
          self._run_prebuild_triggers()
        File "/tmp/pip-install-nfd3s0t1/datatable_a3070a130bc54a49a8069aebae7b80c1/ci/xbuild/extension.py", line 488, in _run_prebuild_triggers
          fn(self)
        File "/tmp/pip-install-nfd3s0t1/datatable_a3070a130bc54a49a8069aebae7b80c1/ci/ext.py", line 369, in generate_documentation
          import gendoc
      ModuleNotFoundError: No module named 'gendoc'
```

**Comment by lisphilar** [comment]
This is due to datatable version 1.0.0 does not support Python 3.10.
Because the datatable version 1.1.0a support Python 3.10, we will use 1.1.0a for a while before 1.1.0 release.
https://github.com/h2oai/datatable/issues/3210
https://github.com/h2oai/datatable/issues/3245

**Comment by lisphilar** [comment]
However, the following error was raised when publishing with `makepypi`.
```Bash
Building covsirphy (2.26.0)
  - Building sdist
  - Built covsirphy-2.26.0.tar.gz
  - Building wheel
  - Built covsirphy-2.26.0-py3-none-any.whl

Publishing covsirphy (2.26.0) to PyPI
 - Uploading covsirphy-2.26.0-py3-none-any.whl FAILED

HTTP Error 400: Invalid value for requires_dist. Error: Can't have direct dependency: 'datatable @ git+https://github.com/h2oai/datatable.git ; python_version >= "3.10" and python_version < "4.0"' | b'<html>\n <head>\n  <title>400 Invalid value for requires_dist. Error: Can\'t have direct dependency: \'datatable @ git+https://github.com/h2oai/datatable.git ; python_version >= "3.10" and python_version < "4.0"\'
```

**Comment by lisphilar** [comment]
pip does not allow installation of a dependency with URL. Until `datatable` v1.1.0 release, we will notify users to install datatable with URL before covsirphy installation.

**Comment by lisphilar** [comment]
This is related to https://github.com/python-poetry/poetry/issues/2828

**Comment by lisphilar** [comment]
Follow-up with #1159 after closing this issue.
