### ISSUE TITLE
[Bug]  URLError when downoading population data with DataDownloader

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#1319]
### Checkbox

- [X] I agree to follow [code of conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html) and to engage in discussion actively.
- [X] I agree to create a new issue with the other templates if this is not a bug.
- [X] I used [the latest version of covsirphy](https://lisphilar.github.io/covid19-sir/markdown/INSTALLATION.html).

### Summary

`URLError` was raised when downoading population data with `DataDownloader` class.

### Reproducible example script

```Python
import covsirphy as cs
print(cs.__version__)
dl = cs.DataDownloader()
dl.layer(databases=["wpp"])
```

### The current outputs

```python
2022-12-25 at 16:03:01 | INFO | Retrieving datasets from World Population Prospects https://population.un.org/wpp/
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/covid19-sir/covsirphy/downloading/downloader.py", line 95, in layer
    new_df = db.layer(country=country, province=province).convert_dtypes()
  File "/covid19-sir/covsirphy/downloading/_db.py", line 56, in layer
    return self._country()
  File "/covid19-sir/covsirphy/downloading/_db_wpp.py", line 42, in _country
    df = self._provide(url=url, suffix="_level1", columns=list(self.COL_DICT.keys()))
  File "/covid19-sir/covsirphy/downloading/_db.py", line 133, in _provide
    df = self._provider.latest(filename=filename, url=url, columns=columns, date=date, date_format=date_format)
  File "/covid19-sir/covsirphy/downloading/_provider.py", line 42, in latest
    df = self.read_csv(url, columns, date=date, date_format=date_format)
  File "/covid19-sir/covsirphy/downloading/_provider.py", line 104, in read_csv
    df = pd.read_csv(path, **kwargs)
  File "/.cache/pypoetry/virtualenvs/covsirphy-UkF5q403-py3.10/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/.cache/pypoetry/virtualenvs/covsirphy-UkF5q403-py3.10/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/.cache/pypoetry/virtualenvs/covsirphy-UkF5q403-py3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/.cache/pypoetry/virtualenvs/covsirphy-UkF5q403-py3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/.cache/pypoetry/virtualenvs/covsirphy-UkF5q403-py3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/.cache/pypoetry/virtualenvs/covsirphy-UkF5q403-py3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/.cache/pypoetry/virtualenvs/covsirphy-UkF5q403-py3.10/lib/python3.10/site-packages/pandas/io/common.py", line 713, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/.cache/pypoetry/virtualenvs/covsirphy-UkF5q403-py3.10/lib/python3.10/site-packages/pandas/io/common.py", line 363, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "/.cache/pypoetry/virtualenvs/covsirphy-UkF5q403-py3.10/lib/python3.10/site-packages/pandas/io/common.py", line 265, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/.anyenv/envs/pyenv/versions/3.10.9/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/.anyenv/envs/pyenv/versions/3.10.9/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/.anyenv/envs/pyenv/versions/3.10.9/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/.anyenv/envs/pyenv/versions/3.10.9/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/.anyenv/envs/pyenv/versions/3.10.9/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/.anyenv/envs/pyenv/versions/3.10.9/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)>
```

### Expected outputs

```python
No errors
```

### Environment

```markdown
- CovsirPhy version: 3.0.0.dev7
- Python version: 3.10.9
```

**Comment by lisphilar** [comment]
The following codes also raise the same error.
```Python
import pandas as pd
pd.read_csv("https://population.un.org/wpp/Download/Files/1_Indicators%20(Standard)/CSV_FILES/WPP2022_TotalPopulationBySex.zip", storage_options={'verify': False})
```

**Comment by lisphilar** [comment]
cf.
https://github.com/urllib3/urllib3/issues/2653
https://docs.python.org/3/library/ssl.html

**Comment by lisphilar** [comment]
The following script showed 200 success code and a dataframe.

```Python
import io
from urllib3 import PoolManager
from urllib3.util.ssl_ import create_urllib3_context
from zipfile import ZipFile
import pandas as pd

URL = "https://population.un.org/wpp/Download/Files/1_Indicators%20(Standard)/CSV_FILES/WPP2022_TotalPopulationBySex.zip"

ctx = create_urllib3_context()
ctx.load_default_certs()
ctx.options |= 0x4  # ssl.OP_LEGACY_SERVER_CONNECT

with PoolManager(ssl_context=ctx) as http:
    r = http.request("GET", URL)
    print(r.status)
    with ZipFile(io.BytesIO(r.data), "r") as fh:
        text = fh.read("WPP2022_TotalPopulationBySex.csv")
    raw = pd.read_csv(io.StringIO(text.decode("utf-8")), low_memory=False)
print(raw)
```
