### ISSUE TITLE
[Fix] Installation error in Kaggle Notebook

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#516]
## Summary
Pip installation of the development version (2.14.0-delta) fails in Kaggle Notebook.

## Codes
```
!pip install --upgrade "git+https://github.com/lisphilar/covid19-sir.git#egg=covsirphy"
```

## Outputs
```Python
Collecting covsirphy
  Cloning https://github.com/lisphilar/covid19-sir.git to /tmp/pip-install-4tyoaqo8/covsirphy_002fe86fe1be48da8d133e889cb86ca7
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python3.7 /opt/conda/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vo9r3iyv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry-core>=1.0.0'
       cwd: None
```

<details><summary><strong>Complete output</strong></summary><div>

```Python
Collecting covsirphy
  Cloning https://github.com/lisphilar/covid19-sir.git to /tmp/pip-install-4tyoaqo8/covsirphy_002fe86fe1be48da8d133e889cb86ca7
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python3.7 /opt/conda/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vo9r3iyv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry-core>=1.0.0'
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/opt/conda/lib/python3.7/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/opt/conda/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 105, in create_command
      module = importlib.import_module(module_path)
    File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/opt/conda/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 18, in <module>
      from pip._internal.index.collector import LinkCollector
    File "/opt/conda/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 125, in <module>
      from . import utils
    File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "/opt/conda/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/opt/conda/lib/python3.7/site-packages/typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/opt/conda/lib/python3.7/site-packages/typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python3.7 /opt/conda/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vo9r3iyv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry-core>=1.0.0' Check the logs for full command output.
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the '/opt/conda/bin/python3.7 -m pip install --upgrade pip' command.
```

</div></details>

## Environment
- CovsirPhy version: 2.14.0-delta
- Python version: 3.7.6
- Installation: pip
- System: Kaggle Notebook

**Comment by lisphilar** [comment]
`!pip install --upgrade pip` did not fix this issue.

**Comment by lisphilar** [comment]
The cause is installation conflict of `typing` and `typing-extentions`. They were included to Python 3.6 or nwer versions, but some dependencies requires to install them as third party packages.
https://github.com/python-poetry/poetry/issues/1258
https://fernandomc.com/posts/issues-with-typing-python-3/

Checked dependencies (not including dev packages) using `poetry.lock` file of CovsirPhy.
1. `dask[complete]` -> `bokeh` -> `typing-extentions`
2. `optuna` -> ... ->` importlib-metadata`

Replacement of `dask[complete]` to `dask[dataframe]` will solve the first one.
The second issue is difficult for us because we heavily depend on `optuna` package.

**Comment by lisphilar** [comment]
Installation of Optuna from GutHub repository in Kaggle notebook shows the same error.
```Python
!pip install --upgrade "git+https://github.com/optuna/optuna.git"
```
`!pip uninstall typing -y` fixed this issue for Optuna.

**Comment by lisphilar** [comment]
`!pip uninstall typing -y` resolved the first error (`AttributeError: type object 'Callable' has no attribute '_abc_registry'`), but new error was raised.
```Python
AttributeError: module 'numpy.linalg.lapack_lite' has no attribute '_ilp64'
```

**Comment by lisphilar** [comment]
With #540, `AttributeError` will be removed.
When using CovsirPhy with Kaggle Notebook, users need to run `!pip uninstall typing -y` in advance.
This will be explained installation guide.
https://lisphilar.github.io/covid19-sir/INSTALLATION.html

**Comment by lisphilar** [comment]
Note:
`!pip uninstall typing -y` is necessary only when using **development versions** of CovsirPhy with Kaggle Notebook.
