### ISSUE TITLE
[Question] Problem when execute steps in quickest_tour

### ISSUE THREAD

**Issue by guilhermegfv** [lisphilar/covid19-sir#713]
## Summary of question

I receive strange results when tring to execute the quickest_tour. Can someone help me with this error?

```>>> _ = snl.simulate()
Traceback (most recent call last):
  File "pandas/_libs/tslibs/parsing.pyx", line 322, in pandas._libs.tslibs.parsing.parse_datetime_string_with_reso
  File "pandas/_libs/tslibs/parsing.pyx", line 503, in pandas._libs.tslibs.parsing.dateutil_parse
ValueError: Unknown datetime string format, unable to parse: 19FEV2020

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axis.py", line 1489, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/usr/local/lib/python3.8/dist-packages/pandas/plotting/_matplotlib/converter.py", line 210, in convert
    values = PeriodConverter._convert_1d(values, units, axis)
  File "/usr/local/lib/python3.8/dist-packages/pandas/plotting/_matplotlib/converter.py", line 219, in _convert_1d
    return get_datevalue(values, axis.freq)
  File "/usr/local/lib/python3.8/dist-packages/pandas/plotting/_matplotlib/converter.py", line 237, in get_datevalue
    return Period(date, freq).ordinal
  File "pandas/_libs/tslibs/period.pyx", line 2397, in pandas._libs.tslibs.period.Period.__new__
  File "pandas/_libs/tslibs/parsing.pyx", line 281, in pandas._libs.tslibs.parsing.parse_time_string
  File "pandas/_libs/tslibs/parsing.pyx", line 327, in pandas._libs.tslibs.parsing.parse_datetime_string_with_reso
pandas._libs.tslibs.parsing.DateParseError: Unknown datetime string format, unable to parse: 19FEV2020

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/covsirphy/analysis/scenario.py", line 777, in simulate
    self.line_plot(
  File "/usr/local/lib/python3.8/dist-packages/covsirphy/analysis/scenario.py", line 201, in line_plot
    return line_plot(df=df, filename=None, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/covsirphy/visualization/line_plot.py", line 172, in line_plot
    lp.line(**find_args([LinePlot.line], **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/covsirphy/visualization/line_plot.py", line 144, in line
    self._ax.axvline(x=value, color=color, linestyle=linestyle)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_axes.py", line 786, in axvline
    xx, = self._process_unit_info([("x", x)], kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_base.py", line 2363, in _process_unit_info
    return [axis_map[axis_name].convert_units(data) if convert else data
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_base.py", line 2363, in <listcomp>
    return [axis_map[axis_name].convert_units(data) if convert else data
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axis.py", line 1491, in convert_units
    raise munits.ConversionError('Failed to convert value(s) to axis '
matplotlib.units.ConversionError: Failed to convert value(s) to axis units: '19fev2020'
>>> ```



## (Optional) What tried

```Python
from pprint import pprint
import covsirphy as cs

data_loader = cs.DataLoader("Test_1004")

jhu_data = data_loader.jhu()

population_data = data_loader.population()

pprint(set(jhu_data.countries()) & set(population_data.countries()), compact=True)

snl = cs.Scenario(country="Japan")
snl.register(jhu_data, population_data)

df = snl.records()
df.tail()

_ = snl.trend()

snl.summary()

snl.estimate(cs.SIRF, timeout=3)

_ = snl.history(target="Rt")

_ = snl.history_rate()

snl.add(days=30)
_ = snl.simulate()
```

## (Optional) Environment

- CovsirPhy version: 2.18.0-epsilon
- Python version: 3.8.5
- Installation: pip
- System: Ubuntu 20.04.2

**Comment by lisphilar** [comment]
Thank you for your kind notice!
I could not find "19fev2020" in CovsirPhy codes and veryu strange.
Could you share the output of `snl.simulate(show_figure=False)` because I could not reproduce the error with my local environment (WSL, Python 3.9.2)?

**Comment by guilhermegfv** [comment]
Thank you for your answer, I tried what you suggested.

It didnt show an error in function snl.simulate, but the error continued according to the log.

```>>> _ = snl.history()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: history() missing 1 required positional argument: 'target'
>>> 
>>> _ = snl.history_rate()
Traceback (most recent call last):
  File "/home/dadf/.local/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 2085, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data)
  File "pandas/_libs/tslibs/conversion.pyx", line 350, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dadf/.local/lib/python3.8/site-packages/covsirphy/analysis/scenario.py", line 1148, in history_rate
    df = self._track_param(name=name)
  File "/home/dadf/.local/lib/python3.8/site-packages/covsirphy/analysis/scenario.py", line 997, in _track_param
    df[self.START] = pd.to_datetime(df[self.START])
  File "/home/dadf/.local/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 805, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/home/dadf/.local/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 465, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/home/dadf/.local/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 2090, in objects_to_datetime64ns
    raise e
  File "/home/dadf/.local/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 2075, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 364, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 591, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 726, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 717, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 243, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/usr/lib/python3/dist-packages/dateutil/parser/_parser.py", line 1356, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/lib/python3/dist-packages/dateutil/parser/_parser.py", line 648, in parse
    raise ValueError("Unknown string format:", timestr)
ValueError: ('Unknown string format:', '06abr2020')
>>> 
>>> snl.add(days=30)
<covsirphy.analysis.scenario.Scenario object at 0x7ff821afa8e0>
>>> 
>>> _ = snl.simulate(show_figure=False)
>>> 
```

**Comment by lisphilar** [comment]
@guilhermegfv,
The error says "19fev2020" (or "06abr2020") is included in the simulated results, but I have no idea why this was included.
Could you copy & paste the output of the following script? `pandas.DataFrame` will be returned with `snl.simulate(show_figure=False)`.
```Python
import covsirphy as cs
data_loader = cs.DataLoader("Test_1004")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
snl = cs.Scenario(country="Japan")
snl.register(jhu_data, population_data)
_ = snl.trend()
snl.estimate(cs.SIRF, timeout=3)
snl.add(days=30)
snl.simulate(show_figure=False)
```

@Inglezos and @rebeccadavidsson,
Is it possible to reproduce this error in your local environment or any platform?

**Comment by rebeccadavidsson** [comment]
Hi! I did not receive an error while running this script, maybe try running it again with a new folder as input? 
```
cs.DataLoader("Test_1005")
```

**Comment by lisphilar** [comment]
Oh, thank you. I did not notice fev and abr are abbreviations in French. CovsirPhy supports only "12Apr2020" format (English) at this time.
It will be necessary to support the other formats and languages to solve this issue.

**Comment by lisphilar** [comment]
@guilhermegfv ,
Does replacement of the older name or the following codes from the stackoverflow answer solve the error in your environment?

```Python
import locale
locale.setlocale(locale.LC_ALL, 'fr_FR')
```

**Comment by lisphilar** [comment]
This issue seems staled?
