### ISSUE TITLE
[Fix] DataLoader(update_interval=None).japan() raises TypeError

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#988]
## Summary
`DataLoader(update_interval=None).japan()` raises `TypeError`.

## Codes

```Python
import covsirphy as cs
# Dataset preparation
loader = cs.DataLoader(update_interval=None)
loader.japan()
```

## Outputs
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/covsirphy/loading/dataloader.py", line 563, in japan
    force = self._download_necessity(filename=filename)
  File "/covsirphy/loading/dataloader.py", line 407, in _download_necessity
    time_limit = date_local + timedelta(hours=self.update_interval)
TypeError: unsupported type for timedelta hours component: NoneType
```

## Environment

- CovsirPhy version: 2.22.2
- Python version: 3.9.8
- Installation: poetry
- System: WSL (Ubuntu)

**Comment by lisphilar** [comment]
`DataLoader(update_interval=None).japan()` is expected to download Japan dataset because the output of `.japan()` is not locked by  `DataLoader().lock()`. (This should be documented in the docstring.) Note that `update_interval=None` means "avoid downloading", but this is for the data locked by `DataLoader().lock()`.
